[tox]
minversion = 4.36.1
envlist =
    py{310,311}-dj42-wagtail{70,72}
    py{310,311,312,313}-dj{52}-wagtail{70,72,73}
    py314-dj52-wagtail73
    coverage-report

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
commands = coverage run --parallel -m pytest {posargs}
extras = test
deps =
    dj42: django>=4.2,<4.3
    dj52: django>=5.2,<5.3
    dj60: django>=6.0,<6.1
    wagtail70: wagtail>=7.0,<7.1
    wagtail72: wagtail>=7.2,<7.3
    wagtail73: wagtail>=7.3,<7.4

[testenv:coverage-report]
basepython = python3.13
deps = coverage
pip_pre = true
skip_install = true
commands =
    coverage combine
    coverage report
