[tox]
minversion = 3.14.6
envlist =
    py{310,311,312}-dj42-wagtail{70,72}
    py{310,311,312,313}-dj{51,52}-wagtail{70,72}
    py{314}-dj52-wagtail{70,72}
    coverage-report

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
commands = coverage run --parallel -m pytest {posargs}
extras = test
deps =
    dj42: django>=4.2,<4.3
    dj51: django>=5.1,<5.2
    dj52: django>=5.2,<5.3
    wagtail70: wagtail>=7.0,<7.1
    wagtail72: wagtail>=7.2,<7.3

[testenv:coverage-report]
basepython = python3.13
deps = coverage
pip_pre = true
skip_install = true
commands =
    coverage combine
    coverage report
