name: Python Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        include:
          - toxenv: "py36-dj22-wagtail29"
            python-version: 3.6
          - toxenv: "py37-dj22-wagtail29"
            python-version: 3.7
          - toxenv: "py37-dj32-wagtail215"
            python-version: 3.7
          - toxenv: "py37-dj32-wagtail216"
            python-version: 3.7
          - toxenv: "py38-dj22-wagtail29"
            python-version: 3.8
          - toxenv: "py38-dj32-wagtail215"
            python-version: 3.8
          - toxenv: "py38-dj32-wagtail216"
            python-version: 3.8
          - toxenv: "py38-dj40-wagtail216"
            python-version: 3.8
          - toxenv: "py38-dj40-wagtail30"
            python-version: 3.8
          - toxenv: "py38-dj40-wagtail40"
            python-version: 3.8
          - toxenv: "py39-dj32-wagtail215"
            python-version: 3.9
          - toxenv: "py39-dj32-wagtail216"
            python-version: 3.9
          - toxenv: "py39-dj32-wagtail30"
            python-version: 3.9
          - toxenv: "py39-dj32-wagtail40"
            python-version: 3.9
          - toxenv: "py310-dj32-wagtail215"
            python-version: "3.10"
          - toxenv: "py310-dj40-wagtail216"
            python-version: "3.10"
          - toxenv: "py310-dj40-wagtail30"
            python-version: "3.10"
          - toxenv: "py310-dj40-wagtail40"
            python-version: "3.10"
          - toxenv: "py310-dj41-wagtail40"
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Run tox - ${{ matrix.toxenv }}
      env:
        TOX_ENV: ${{ matrix.toxenv }}
      run: |
        tox -e $TOX_ENV
